# Terraform Hyperping CI/CD Workflow
# Copy this file to your repository: .github/workflows/terraform-hyperping.yml
#
# Prerequisites:
# 1. Set HYPERPING_API_KEY secret in your repository settings
# 2. (Optional) Configure Terraform Cloud/S3 backend for state management
#
# Usage:
# - Push to main: Plan and apply changes
# - Pull request: Plan only (no apply)
# - Manual trigger: Choose to plan or apply

name: Terraform Hyperping

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform-hyperping.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

# Prevent concurrent runs on the same branch
concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false  # Never cancel running applies!

env:
  TF_VERSION: '1.8.0'
  TF_IN_AUTOMATION: 'true'
  # Reduce parallelism to avoid rate limits
  TF_CLI_ARGS_plan: '-parallelism=5'
  TF_CLI_ARGS_apply: '-parallelism=5'

jobs:
  # ============================================
  # VALIDATE: Check Terraform configuration
  # ============================================
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  # ============================================
  # PLAN: Generate execution plan
  # ============================================
  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      has_changes: ${{ steps.plan.outputs.has_changes }}
    env:
      HYPERPING_API_KEY: ${{ secrets.HYPERPING_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -detailed-exitcode -out=tfplan || exit_code=$?

          if [ "$exit_code" == "0" ]; then
            echo "No changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          elif [ "$exit_code" == "2" ]; then
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "Plan failed"
            exit 1
          fi

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          retention-days: 5

      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            const plan = execSync('terraform show -no-color tfplan').toString();

            const output = `#### Terraform Plan

            <details>
            <summary>Show Plan</summary>

            \`\`\`hcl
            ${plan.substring(0, 65000)}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

  # ============================================
  # APPLY: Apply changes (main branch only)
  # ============================================
  apply:
    name: Apply
    runs-on: ubuntu-latest
    needs: plan
    if: |
      (github.ref == 'refs/heads/main' && github.event_name == 'push' && needs.plan.outputs.has_changes == 'true') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
    environment: production  # Requires approval if configured
    env:
      HYPERPING_API_KEY: ${{ secrets.HYPERPING_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Post-Apply Verification
        run: |
          echo "Verifying state..."
          terraform state list
          echo "Apply completed successfully!"

  # ============================================
  # DESTROY: Destroy resources (manual only)
  # ============================================
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
    environment: production  # Requires approval
    env:
      HYPERPING_API_KEY: ${{ secrets.HYPERPING_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

  # ============================================
  # DRIFT: Check for configuration drift
  # ============================================
  drift-check:
    name: Drift Check
    runs-on: ubuntu-latest
    # Run on schedule (uncomment to enable)
    # if: github.event_name == 'schedule'
    if: false  # Disabled by default - enable for scheduled runs
    env:
      HYPERPING_API_KEY: ${{ secrets.HYPERPING_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Check for Drift
        id: drift
        run: |
          terraform plan -detailed-exitcode || exit_code=$?

          if [ "$exit_code" == "2" ]; then
            echo "Configuration drift detected!"
            echo "drift_detected=true" >> $GITHUB_OUTPUT
          else
            echo "No drift detected"
            echo "drift_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Issue on Drift
        if: steps.drift.outputs.drift_detected == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Terraform Drift Detected',
              body: 'Configuration drift was detected in Hyperping resources. Please review and reconcile.',
              labels: ['terraform', 'drift']
            });
