apiVersion: v1
kind: Service
metadata:
  name: hyperping-exporter
  namespace: monitoring
  labels:
    app: hyperping-exporter
spec:
  selector:
    app: hyperping-exporter
  ports:
    - name: metrics
      port: 9312
      targetPort: metrics
      protocol: TCP
  type: ClusterIP
