name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: terraform-config
    attributes:
      label: Terraform Configuration
      description: Please provide your Terraform configuration (remove sensitive data).
      placeholder: |
        terraform {
          required_providers {
            hyperping = {
              source = "develeap/hyperping"
              version = "~> 1.0"
            }
          }
        }

        resource "hyperping_monitor" "example" {
          # your configuration
        }
      render: hcl
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Apply the configuration above
        2. Run terraform plan
        3. See error
    validations:
      required: true

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: Output of `terraform version`
      placeholder: "Terraform v1.8.0"
    validations:
      required: true

  - type: input
    id: provider-version
    attributes:
      label: Provider Version
      description: Which version of the provider are you using?
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Debug Logs
      description: |
        Please provide debug logs if available. Run with `TF_LOG=DEBUG terraform apply` and paste relevant output.
        **Important:** Remove any sensitive information (API keys, passwords, etc.)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem.
