name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide details about what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the use case?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: |
        I would like to see a new resource/data source that...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Configuration
      description: If applicable, show how you envision using this feature.
      placeholder: |
        resource "hyperping_new_feature" "example" {
          name = "example"
          # ...
        }
      render: hcl

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - New Resource
        - New Data Source
        - Enhancement to Existing Resource
        - Enhancement to Existing Data Source
        - Documentation Improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Would you like to implement this feature?
      options:
        - "Yes, I'd like to implement this"
        - "I can help with testing"
        - "No, but I'd use it"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or information about the feature request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
